require("masterfork_rcp_tweaks")
require("masterfork_rcp_worship")
require("masterfork_rcp_injector")
require("masterfork_secret_necromancy")
require("masterfork_curse_vampirism")
require("masterfork_scripts")