interactions.curse.major.vampire=nil-- disables vanilla vampires

-- redefined vampires
interactions.curse.major.vampire=function(idx,tok)
    return {raws={
    "[IS_HIST_STRING_1: cursed ]",
    "[IS_HIST_STRING_2: to prowl the night in search of blood]",
    "[IS_TRIGGER_STRING_SECOND:have]",
    "[IS_TRIGGER_STRING_THIRD:has]",
    "[IS_TRIGGER_STRING:been cursed to prowl the night in search of blood!]",
"[I_SOURCE:INGESTION]",
    "[IS_HIST_STRING_1: consumed the tainted blood of ]",
    "[IS_HIST_STRING_2: and was cursed]",
"[I_SOURCE:ATTACK]",--new
    "[IS_HIST_STRING_1: bit ]",
    "[IS_HIST_STRING_2: passing on the vampire curse]",
"[I_TARGET:A:CREATURE]",
    "[IT_LOCATION:CONTEXT_CREATURE]",
    "[IT_REQUIRES:CAN_LEARN]",
    "[IT_REQUIRES:HAS_BLOOD]",
    "[IT_FORBIDDEN:NOT_LIVING]",
    "[IT_FORBIDDEN:SUPERNATURAL]",
    "[IT_CANNOT_HAVE_SYNDROME_CLASS:WERECURSE]",
    "[IT_CANNOT_HAVE_SYNDROME_CLASS:VAMPCURSE]",
    "[IT_CANNOT_HAVE_SYNDROME_CLASS:DISTURBANCE_CURSE]",
    "[IT_CANNOT_HAVE_SYNDROME_CLASS:RAISED_UNDEAD]",
    "[IT_CANNOT_HAVE_SYNDROME_CLASS:RAISED_GHOST]",
    "[IT_CANNOT_HAVE_SYNDROME_CLASS:GHOUL]",
"[I_EFFECT:ADD_SYNDROME]",
    "[IE_TARGET:A]",
    "[IE_IMMEDIATE]",
    "[IE_ARENA_NAME:Vampire]",
    "[SYNDROME]",
    --SOME STANDARD UNDEAD PROPERTIES, BUT NOT ALL OF THEM
        "[SYN_CLASS:VAMPCURSE]",
        "[SYN_CONCENTRATION_ADDED:1000:0]",--just in case
		"[SYN_NO_HOSPITAL]",--new
        "[CE_ADD_TAG:BLOODSUCKER:NO_AGING:STERILE:NOT_LIVING:NOEXERT:NOPAIN:NOBREATHE:NOSTUN:NONAUSEA:NO_DIZZINESS:NO_FEVERS:PARALYZEIMMUNE:NO_EAT:NO_DRINK:NO_SLEEP:NO_PHYS_ATT_GAIN:NO_PHYS_ATT_RUST:START:0:ABRUPT]",
		"[CE_PHYS_ATT_CHANGE:STRENGTH:50:0:TOUGHNESS:50:0:AGILITY:50:0:ENDURANCE:50:0:DISEASE_RESISTANCE:50:0:START:0:ABRUPT]",-- weakens the target always
		"[CE_MENT_ATT_CHANGE:EMPATHY:75:-150]",-- vampires are less empathetic
		"[CE_SPEED_CHANGE:SPEED_PERC:80:START:0:ABRUPT]",
		"[CE_MENT_ATT_CHANGE:FOCUS:50:0:START:0:ABRUPT]",
		"[CE_MENT_ATT_CHANGE:INTUITION:50:0:START:0:ABRUPT]",
		"[CE_MENT_ATT_CHANGE:SPATIAL_SENSE:50:0:START:0:ABRUPT]",
		"[CE_MENT_ATT_CHANGE:KINESTHETIC_SENSE:50:0:START:0:ABRUPT]",
		"[CE_MENT_ATT_CHANGE:WILLPOWER:50:0:START:0:ABRUPT]",
		"[CE_SPECIAL_ATTACK_INTERACTION:INTERACTION:"..tok..":BP:BY_CATEGORY:MOUTH:BP:BY_CATEGORY:TOOTH:START:0:ABRUPT]",-- vampires can spread vampirism similar to werecreatures
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:NONE:NONE:1:2:ABRUPT]",-- 0.5x damage taken from all materials
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:INORGANIC:STEEL:1:1:ABRUPT]",-- 1.0x damage taken from steel
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:INORGANIC:BRONZE:4:5]",-- 0.75x damage taken from bronze
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:INORGANIC:SILVER:6:4:ABRUPT]",-- 1.5x damage taken from silver
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:INORGANIC:MITHRIL:5:4:ABRUPT]",-- 1.25x damage taken from mithril
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:INORGANIC:DWARFSTEEL:5:4:ABRUPT]",-- 1.25x damage taken from dwarfsteel
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:INORGANIC:TITANSTEEL:5:4:ABRUPT]",-- 1.25x damage taken from titansteel
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:INORGANIC:ORICHALCUM:5:4:ABRUPT]",-- 1.25x damage taken from orichalcum
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:INORGANIC:VOLCANIC:5:4:ABRUPT]",--   1.25x damage taken from volcanite
		"[CE_MATERIAL_FORCE_MULTIPLIER:MAT_MULT:INORGANIC:ADAMANTINE:5:4:ABRUPT]",-- 1.25x damage taken from adamantine
        "[CE_BODY_MAT_INTERACTION:MAT_TOKEN:RESERVED_BLOOD:START:0:ABRUPT]",
        "[CE:INTERACTION:"..tok.."]",
            "[CE:SYNDROME_TAG:SYN_INGESTED]",
                    "[CE:SYNDROME_TAG:SYN_INJECTED]",
        "[CE_DISPLAY_TILE:TILE:165:4:0:0:START:0:CAN_BE_HIDDEN:ABRUPT]",
		"[CE_CHANGE_PERSONALITY:FACET:ANXIETY_PROPENSITY:25:FACET:LOVE_PROPENSITY:-25:FACET:BASHFUL:25:FACET:PRIVACY:50:FACET:TRUST:-50:FACET:TOLERANT:25:FACET:EMOTIONALLY_OBSESSIVE:-25:FACET:SWAYED_BY_EMOTIONS:-25:START:0:ABRUPT]",-- new personality facets
		"[CE_MENT_ATT_CHANGE:EMPATHY:80:0]",-- vampires are less empathetic
        "[CE_DISPLAY_NAME:NAME:vampire:vampires:vampiric:START:0:CAN_BE_HIDDEN:ABRUPT]",
        "[CE_BP_APPEARANCE_MODIFIER:START:0:BP:BY_CATEGORY:TOOTH:APPEARANCE_MODIFIER:LENGTH:150:ABRUPT]",
            "[CE:COUNTER_TRIGGER:DRINKING_BLOOD:1:NONE:REQUIRED]",
		"[CE_BP_APPEARANCE_MODIFIER:START:0:BP:BY_CATEGORY:TOOTH:APPEARANCE_MODIFIER:BROADNESS:75:ABRUPT]",-- new narrower teeth
			"[CE:COUNTER_TRIGGER:DRINKING_BLOOD:1:NONE:REQUIRED]",
        "[CE_SENSE_CREATURE_CLASS:START:0:CLASS:GENERAL_POISON:15:4:0:1:ABRUPT]",
		"[CE_PHYS_ATT_CHANGE:STRENGTH:250:100:TOUGHNESS:250:100:AGILITY:250:100:ENDURANCE:250:100:DISEASE_RESISTANCE:250:100:START:0:ABRUPT]",-- strengthens the target
			"[CE:COUNTER_TRIGGER:TIME_SINCE_SUCKED_BLOOD:NONE:2400:REQUIRED:DWF_STRETCH:144]",-- 2 day duration, prevents the above strengthening effect from working unless the target has recently sucked blood vampires become thirsty at 1200
		"[CE_SPEED_CHANGE:SPEED_PERC:120:START:0:ABRUPT]",
			"[CE:COUNTER_TRIGGER:TIME_SINCE_SUCKED_BLOOD:NONE:2400:REQUIRED:DWF_STRETCH:144]",
		"[CE_MENT_ATT_CHANGE:FOCUS:250:100:START:0:ABRUPT]",
			"[CE:COUNTER_TRIGGER:TIME_SINCE_SUCKED_BLOOD:NONE:2400:REQUIRED:DWF_STRETCH:144]",
		"[CE_MENT_ATT_CHANGE:INTUITION:250:100:START:0:ABRUPT]",
			"[CE:COUNTER_TRIGGER:TIME_SINCE_SUCKED_BLOOD:NONE:2400:REQUIRED:DWF_STRETCH:144]",
		"[CE_MENT_ATT_CHANGE:SPATIAL_SENSE:250:100:START:0:ABRUPT]",
			"[CE:COUNTER_TRIGGER:TIME_SINCE_SUCKED_BLOOD:NONE:2400:REQUIRED:DWF_STRETCH:144]",
		"[CE_MENT_ATT_CHANGE:KINESTHETIC_SENSE:250:100:START:0:ABRUPT]",
			"[CE:COUNTER_TRIGGER:TIME_SINCE_SUCKED_BLOOD:NONE:2400:REQUIRED:DWF_STRETCH:144]",
		"[CE_MENT_ATT_CHANGE:WILLPOWER:250:100:START:0:ABRUPT]",
			"[CE:COUNTER_TRIGGER:TIME_SINCE_SUCKED_BLOOD:NONE:2400:REQUIRED:DWF_STRETCH:144]",
		"[CE_ADD_TAG:CRAZED]",--goes berserk after 6 months of no blood
			"[CE:COUNTER_TRIGGER:TIME_SINCE_SUCKED_BLOOD:NONE:201600:REQUIRED:DWF_STRETCH:144]",
		"[CE_REMOVE_TAG:NOEXERT:NOPAIN:NOSTUN:NONAUSEA:EXTRAVISION:NO_DIZZINESS:NO_FEVERS:NO_PHYS_ATT_RUST:START:0:ABRUPT]",
			"[CE:COUNTER_TRIGGER:TIME_SINCE_SUCKED_BLOOD:NONE:201600:REQUIRED:DWF_STRETCH:144]",
		"[CE_CAN_DO_INTERACTION:START:0:ABRUPT]",-- new vanish ability
		    "[CDI:ADV_NAME:Vanish]",
		    "[CDI:INTERACTION:VAMP_STEALTH]",
		    "[CDI:TARGET:A:SELF_ONLY]",
		    "[CDI:TARGET_RANGE:A:1]",
		    "[CDI:USAGE_HINT:FLEEING]",
		    "[CDI:VERB:begin to vanish:begins to vanish:NA]",
		    "[CDI:TARGET_VERB:vanish completely:vanishes completely]",
		    "[CDI:WAIT_PERIOD:172800]",
		"[CE_CAN_DO_INTERACTION]",-- new regeneration ability
		    "[CDI:ADV_NAME:Regenerate]",
			"[CDI:INTERACTION:REGENERATE_CREATURE]",
		    "[CDI:USAGE_HINT:FLEEING]",
		    "[CDI:USAGE_HINT:DEFEND]",
		    "[CDI:BP_REQUIRED:BY_CATEGORY:HEAD]",
		    "[CDI:VERB:reform your body:begins to reform:begin to reform]",
		    "[CDI:TARGET:A:SELF_ONLY:TOUCHABLE]",
		    "[CDI:TARGET_RANGE:A:1]",
		    "[CDI:MAX_TARGET_NUMBER:A:1]",
		    "[CDI:FREE_ACTION]",
		    "[CDI:WAIT_PERIOD:172800]",
    },weight=1}
end